
package cn.ccccltd.webservice.dict;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:25:25.008+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class ViewDictonaryWs_ViewDictonaryWsImplPort_Server{

    protected ViewDictonaryWs_ViewDictonaryWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ViewDictonaryWsImplPortImpl();
        String address = "http://192.168.0.138:8090/waf_ws/ws/dict";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ViewDictonaryWs_ViewDictonaryWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
