package cn.ccccltd.webservice.other.monthreport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-17T09:32:34.095+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", name = "QtxmzxWs")
@XmlSeeAlso({ObjectFactory.class})
public interface QtxmzxWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateMonthReport", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.UpdateMonthReport")
    @WebMethod(action = "http://monthreport.other.webservice.ccccltd.cn/updateMonthReport")
    @ResponseWrapper(localName = "updateMonthReportResponse", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.UpdateMonthReportResponse")
    public cn.ccccltd.webservice.other.monthreport.ReturnMessage updateMonthReport(
        @WebParam(name = "monthReportInfo", targetNamespace = "")
        cn.ccccltd.webservice.other.monthreport.QtxmzxVO monthReportInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryMonthReport", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.QueryMonthReport")
    @WebMethod(action = "http://monthreport.other.webservice.ccccltd.cn/queryMonthReport")
    @ResponseWrapper(localName = "queryMonthReportResponse", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.QueryMonthReportResponse")
    public cn.ccccltd.webservice.other.monthreport.ReturnMessage queryMonthReport(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "datatime", targetNamespace = "")
        java.lang.String datatime
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryMonthReportById", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.QueryMonthReportById")
    @WebMethod(action = "http://monthreport.other.webservice.ccccltd.cn/queryMonthReportById")
    @ResponseWrapper(localName = "queryMonthReportByIdResponse", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.QueryMonthReportByIdResponse")
    public cn.ccccltd.webservice.other.monthreport.ReturnMessage queryMonthReportById(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "jtRevenueId", targetNamespace = "")
        java.lang.String jtRevenueId,
        @WebParam(name = "jtContractId", targetNamespace = "")
        java.lang.String jtContractId
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addMonthReport", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.AddMonthReport")
    @WebMethod(action = "http://monthreport.other.webservice.ccccltd.cn/addMonthReport")
    @ResponseWrapper(localName = "addMonthReportResponse", targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.monthreport.AddMonthReportResponse")
    public cn.ccccltd.webservice.other.monthreport.ReturnMessage addMonthReport(
        @WebParam(name = "monthReportInfo", targetNamespace = "")
        cn.ccccltd.webservice.other.monthreport.QtxmzxVO monthReportInfo
    );
}
