
package cn.ccccltd.webservice.other.monthreport;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-17T09:32:34.104+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class QtxmzxWs_QtxmzxWsImplPort_Server{

    protected QtxmzxWs_QtxmzxWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QtxmzxWsImplPortImpl();
        String address = "http://192.168.0.174:8090/waf/ws/other_monthReport";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QtxmzxWs_QtxmzxWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
