package cn.ccccltd.webservice.dict;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:25:25.012+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "viewDictonaryWsImpl", 
                  wsdlLocation = "http://192.168.0.138:8090/waf_ws/ws/dict?wsdl",
                  targetNamespace = "http://dict.webservice.ccccltd.cn/") 
public class ViewDictonaryWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dict.webservice.ccccltd.cn/", "viewDictonaryWsImpl");
    public final static QName ViewDictonaryWsImplPort = new QName("http://dict.webservice.ccccltd.cn/", "ViewDictonaryWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.138:8090/waf_ws/ws/dict?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ViewDictonaryWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.138:8090/waf_ws/ws/dict?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ViewDictonaryWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ViewDictonaryWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ViewDictonaryWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ViewDictonaryWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ViewDictonaryWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ViewDictonaryWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ViewDictonaryWs
     */
    @WebEndpoint(name = "ViewDictonaryWsImplPort")
    public ViewDictonaryWs getViewDictonaryWsImplPort() {
        return super.getPort(ViewDictonaryWsImplPort, ViewDictonaryWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ViewDictonaryWs
     */
    @WebEndpoint(name = "ViewDictonaryWsImplPort")
    public ViewDictonaryWs getViewDictonaryWsImplPort(WebServiceFeature... features) {
        return super.getPort(ViewDictonaryWsImplPort, ViewDictonaryWs.class, features);
    }

}
