
package cn.ccccltd.webservice.construction.projectbaseinfo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-26T13:09:40.320+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class GhscgzjzbWs_GhscgzjzbWsImplPort_Server{

    protected GhscgzjzbWs_GhscgzjzbWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GhscgzjzbWsImplPortImpl();
        String address = "http://localhost:8060/waf/ws/invest_productBaseInfo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new GhscgzjzbWs_GhscgzjzbWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
