
package cn.ccccltd.webservice.dict;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:25:24.947+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class ViewDictonaryWs_ViewDictonaryWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://dict.webservice.ccccltd.cn/", "viewDictonaryWsImpl");

    private ViewDictonaryWs_ViewDictonaryWsImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ViewDictonaryWsImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ViewDictonaryWsImpl ss = new ViewDictonaryWsImpl(wsdlURL, SERVICE_NAME);
        ViewDictonaryWs port = ss.getViewDictonaryWsImplPort();  
        
        {
        System.out.println("Invoking getDict...");
        java.lang.String _getDict_dictCode = "";
        java.lang.String _getDict_dictName = "";
        java.lang.String _getDict_dictType = "";
        cn.ccccltd.webservice.dict.ReturnMessage _getDict__return = port.getDict(_getDict_dictCode, _getDict_dictName, _getDict_dictType);
        System.out.println("getDict.result=" + _getDict__return);


        }

        System.exit(0);
    }

}
