package cn.ccccltd.webservice.org;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:35:24.765+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://org.webservice.ccccltd.cn/", name = "MdorgWs")
@XmlSeeAlso({ObjectFactory.class})
public interface MdorgWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getOrg", targetNamespace = "http://org.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.org.GetOrg")
    @WebMethod(action = "http://org.webservice.ccccltd.cn/getOrg")
    @ResponseWrapper(localName = "getOrgResponse", targetNamespace = "http://org.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.org.GetOrgResponse")
    public cn.ccccltd.webservice.org.ReturnMessage getOrg(
        @WebParam(name = "orgcode", targetNamespace = "")
        java.lang.String orgcode,
        @WebParam(name = "orgname", targetNamespace = "")
        java.lang.String orgname,
        @WebParam(name = "parentcode", targetNamespace = "")
        java.lang.String parentcode,
        @WebParam(name = "parentname", targetNamespace = "")
        java.lang.String parentname
    );
}
