package cn.ccccltd.webservice.other.monthreport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-17T09:32:34.110+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "qtxmzxWsImpl", 
                  wsdlLocation = "http://192.168.0.174:8090/waf/ws/other_monthReport?wsdl",
                  targetNamespace = "http://monthreport.other.webservice.ccccltd.cn/") 
public class QtxmzxWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://monthreport.other.webservice.ccccltd.cn/", "qtxmzxWsImpl");
    public final static QName QtxmzxWsImplPort = new QName("http://monthreport.other.webservice.ccccltd.cn/", "QtxmzxWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.174:8090/waf/ws/other_monthReport?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(QtxmzxWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.174:8090/waf/ws/other_monthReport?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public QtxmzxWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QtxmzxWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QtxmzxWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public QtxmzxWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public QtxmzxWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public QtxmzxWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QtxmzxWs
     */
    @WebEndpoint(name = "QtxmzxWsImplPort")
    public QtxmzxWs getQtxmzxWsImplPort() {
        return super.getPort(QtxmzxWsImplPort, QtxmzxWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QtxmzxWs
     */
    @WebEndpoint(name = "QtxmzxWsImplPort")
    public QtxmzxWs getQtxmzxWsImplPort(WebServiceFeature... features) {
        return super.getPort(QtxmzxWsImplPort, QtxmzxWs.class, features);
    }

}
