
package cn.ccccltd.webservice.construction.marketinfo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-15T16:13:53.353+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class GhscxxWs_GhscxxWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://marketinfo.construction.webservice.ccccltd.cn/", "ghscxxWsImpl");

    private GhscxxWs_GhscxxWsImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GhscxxWsImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GhscxxWsImpl ss = new GhscxxWsImpl(wsdlURL, SERVICE_NAME);
        GhscxxWs port = ss.getGhscxxWsImplPort();  
        
        {
        System.out.println("Invoking updateMarketInfo...");
        cn.ccccltd.webservice.construction.marketinfo.GhscxxVO _updateMarketInfo_projectMarketInfo = null;
        cn.ccccltd.webservice.construction.marketinfo.ReturnMessage _updateMarketInfo__return = port.updateMarketInfo(_updateMarketInfo_projectMarketInfo);
        System.out.println("updateMarketInfo.result=" + _updateMarketInfo__return);


        }
        {
        System.out.println("Invoking queryMarketInfoById...");
        java.lang.String _queryMarketInfoById_zzjg = "";
        java.lang.String _queryMarketInfoById_recid = "";
        cn.ccccltd.webservice.construction.marketinfo.ReturnMessage _queryMarketInfoById__return = port.queryMarketInfoById(_queryMarketInfoById_zzjg, _queryMarketInfoById_recid);
        System.out.println("queryMarketInfoById.result=" + _queryMarketInfoById__return);


        }
        {
        System.out.println("Invoking addMarketInfo...");
        cn.ccccltd.webservice.construction.marketinfo.GhscxxVO _addMarketInfo_projectMarketInfo = null;
        cn.ccccltd.webservice.construction.marketinfo.ReturnMessage _addMarketInfo__return = port.addMarketInfo(_addMarketInfo_projectMarketInfo);
        System.out.println("addMarketInfo.result=" + _addMarketInfo__return);


        }

        System.exit(0);
    }

}
