package cn.ccccltd.webservice.design.contractchange;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:21:50.217+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "sjbghtWsImpl", 
                  wsdlLocation = "http://10.17.16.33:7070/waf/ws/design_contractChange?wsdl",
                  targetNamespace = "http://contractchange.design.webservice.ccccltd.cn/") 
public class SjbghtWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://contractchange.design.webservice.ccccltd.cn/", "sjbghtWsImpl");
    public final static QName SjbghtWsImplPort = new QName("http://contractchange.design.webservice.ccccltd.cn/", "SjbghtWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.17.16.33:7070/waf/ws/design_contractChange?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SjbghtWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.17.16.33:7070/waf/ws/design_contractChange?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SjbghtWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SjbghtWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SjbghtWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SjbghtWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SjbghtWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SjbghtWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SjbghtWs
     */
    @WebEndpoint(name = "SjbghtWsImplPort")
    public SjbghtWs getSjbghtWsImplPort() {
        return super.getPort(SjbghtWsImplPort, SjbghtWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SjbghtWs
     */
    @WebEndpoint(name = "SjbghtWsImplPort")
    public SjbghtWs getSjbghtWsImplPort(WebServiceFeature... features) {
        return super.getPort(SjbghtWsImplPort, SjbghtWs.class, features);
    }

}
