
package cn.ccccltd.webservice.construction.contract;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-22T14:43:14.127+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class GhxmjhtWs_GhxmjhtWsImplPort_Server{

    protected GhxmjhtWs_GhxmjhtWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GhxmjhtWsImplPortImpl();
        String address = "http://192.168.0.161:8090/waf/ws/invest_contractInfo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new GhxmjhtWs_GhxmjhtWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
