
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.ccccltd.webservice.org;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:35:24.745+08:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "mdorgWsImpl",
                      portName = "MdorgWsImplPort",
                      targetNamespace = "http://org.webservice.ccccltd.cn/",
                      wsdlLocation = "http://192.168.0.138:8090/waf_ws/ws/org?wsdl",
                      endpointInterface = "cn.ccccltd.webservice.org.MdorgWs")
                      
public class MdorgWsImplPortImpl implements MdorgWs {

    private static final Logger LOG = Logger.getLogger(MdorgWsImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.org.MdorgWs#getOrg(java.lang.String orgcode, java.lang.String orgname, java.lang.String parentcode, java.lang.String parentname)*
     */
    public cn.ccccltd.webservice.org.ReturnMessage getOrg(java.lang.String orgcode, java.lang.String orgname, java.lang.String parentcode, java.lang.String parentname) { 
        LOG.info("Executing operation getOrg");
        System.out.println(orgcode);
        System.out.println(orgname);
        System.out.println(parentcode);
        System.out.println(parentname);
        try {
            cn.ccccltd.webservice.org.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
