
package cn.ccccltd.webservice.design.marketinfo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-14T16:55:50.921+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class SjscxxWs_SjscxxWsImplPort_Server{

    protected SjscxxWs_SjscxxWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SjscxxWsImplPortImpl();
        String address = "http://localhost:8060/waf/ws/design_productMarektInfo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SjscxxWs_SjscxxWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
