
package cn.ccccltd.webservice.other.projectbaseinfo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-26T13:12:45.480+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class QtlxmWs_QtlxmWsImplPort_Server{

    protected QtlxmWs_QtlxmWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QtlxmWsImplPortImpl();
        String address = "http://localhost:8060/waf/ws/other_productBaseInfo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QtlxmWs_QtlxmWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
