
package cn.ccccltd.webservice.org;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:35:24.711+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class MdorgWs_MdorgWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://org.webservice.ccccltd.cn/", "mdorgWsImpl");

    private MdorgWs_MdorgWsImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MdorgWsImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MdorgWsImpl ss = new MdorgWsImpl(wsdlURL, SERVICE_NAME);
        MdorgWs port = ss.getMdorgWsImplPort();  
        
        {
        System.out.println("Invoking getOrg...");
        java.lang.String _getOrg_orgcode = "";
        java.lang.String _getOrg_orgname = "";
        java.lang.String _getOrg_parentcode = "";
        java.lang.String _getOrg_parentname = "";
        cn.ccccltd.webservice.org.ReturnMessage _getOrg__return = port.getOrg(_getOrg_orgcode, _getOrg_orgname, _getOrg_parentcode, _getOrg_parentname);
        System.out.println("getOrg.result=" + _getOrg__return);


        }

        System.exit(0);
    }

}
