package cn.ccccltd.webservice.org;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:35:24.795+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "mdorgWsImpl", 
                  wsdlLocation = "http://192.168.0.138:8090/waf_ws/ws/org?wsdl",
                  targetNamespace = "http://org.webservice.ccccltd.cn/") 
public class MdorgWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://org.webservice.ccccltd.cn/", "mdorgWsImpl");
    public final static QName MdorgWsImplPort = new QName("http://org.webservice.ccccltd.cn/", "MdorgWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.138:8090/waf_ws/ws/org?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MdorgWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.138:8090/waf_ws/ws/org?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MdorgWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MdorgWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MdorgWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MdorgWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MdorgWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MdorgWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MdorgWs
     */
    @WebEndpoint(name = "MdorgWsImplPort")
    public MdorgWs getMdorgWsImplPort() {
        return super.getPort(MdorgWsImplPort, MdorgWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MdorgWs
     */
    @WebEndpoint(name = "MdorgWsImplPort")
    public MdorgWs getMdorgWsImplPort(WebServiceFeature... features) {
        return super.getPort(MdorgWsImplPort, MdorgWs.class, features);
    }

}
