
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.ccccltd.webservice.design.monthreport;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-17T09:31:12.934+08:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "sjxmzxfdWsImpl",
                      portName = "SjxmzxfdWsImplPort",
                      targetNamespace = "http://monthreport.design.webservice.ccccltd.cn/",
                      wsdlLocation = "http://192.168.0.174:8090/waf/ws/design_monthReport?wsdl",
                      endpointInterface = "cn.ccccltd.webservice.design.monthreport.SjxmzxfdWs")
                      
public class SjxmzxfdWsImplPortImpl implements SjxmzxfdWs {

    private static final Logger LOG = Logger.getLogger(SjxmzxfdWsImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.design.monthreport.SjxmzxfdWs#queryMonthReportById(java.lang.String zzjg, java.lang.String jtRevenueId, java.lang.String jtContractId)*
     */
    public cn.ccccltd.webservice.design.monthreport.ReturnMessage queryMonthReportById(java.lang.String zzjg, java.lang.String jtRevenueId, java.lang.String jtContractId) { 
        LOG.info("Executing operation queryMonthReportById");
        System.out.println(zzjg);
        System.out.println(jtRevenueId);
        System.out.println(jtContractId);
        try {
            cn.ccccltd.webservice.design.monthreport.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.design.monthreport.SjxmzxfdWs#addMonthReport(cn.ccccltd.webservice.design.monthreport.SjxmzxfdVO monthReportInfo)*
     */
    public cn.ccccltd.webservice.design.monthreport.ReturnMessage addMonthReport(cn.ccccltd.webservice.design.monthreport.SjxmzxfdVO monthReportInfo) { 
        LOG.info("Executing operation addMonthReport");
        System.out.println(monthReportInfo);
        try {
            cn.ccccltd.webservice.design.monthreport.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.design.monthreport.SjxmzxfdWs#updateMonthReport(cn.ccccltd.webservice.design.monthreport.SjxmzxfdVO monthReportInfo)*
     */
    public cn.ccccltd.webservice.design.monthreport.ReturnMessage updateMonthReport(cn.ccccltd.webservice.design.monthreport.SjxmzxfdVO monthReportInfo) { 
        LOG.info("Executing operation updateMonthReport");
        System.out.println(monthReportInfo);
        try {
            cn.ccccltd.webservice.design.monthreport.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.design.monthreport.SjxmzxfdWs#queryMonthReport(java.lang.String zzjg, java.lang.String datatime)*
     */
    public cn.ccccltd.webservice.design.monthreport.ReturnMessage queryMonthReport(java.lang.String zzjg, java.lang.String datatime) { 
        LOG.info("Executing operation queryMonthReport");
        System.out.println(zzjg);
        System.out.println(datatime);
        try {
            cn.ccccltd.webservice.design.monthreport.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
