
package cn.ccccltd.webservice.construction.contractchange;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:50:20.995+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class SgbghtWs_SgbghtWsImplPort_Server{

    protected SgbghtWs_SgbghtWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SgbghtWsImplPortImpl();
        String address = "http://10.17.16.33:7070/waf/ws/invest_contractChange";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SgbghtWs_SgbghtWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
