package cn.ccccltd.webservice.construction.monthreport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-17T09:29:10.111+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "ghxmzxfdWsImpl", 
                  wsdlLocation = "http://192.168.0.174:8090/waf/ws/construction_monthReport?wsdl",
                  targetNamespace = "http://monthreport.construction.webservice.ccccltd.cn/") 
public class GhxmzxfdWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://monthreport.construction.webservice.ccccltd.cn/", "ghxmzxfdWsImpl");
    public final static QName GhxmzxfdWsImplPort = new QName("http://monthreport.construction.webservice.ccccltd.cn/", "GhxmzxfdWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.174:8090/waf/ws/construction_monthReport?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GhxmzxfdWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.174:8090/waf/ws/construction_monthReport?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GhxmzxfdWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GhxmzxfdWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GhxmzxfdWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GhxmzxfdWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GhxmzxfdWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GhxmzxfdWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GhxmzxfdWs
     */
    @WebEndpoint(name = "GhxmzxfdWsImplPort")
    public GhxmzxfdWs getGhxmzxfdWsImplPort() {
        return super.getPort(GhxmzxfdWsImplPort, GhxmzxfdWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GhxmzxfdWs
     */
    @WebEndpoint(name = "GhxmzxfdWsImplPort")
    public GhxmzxfdWs getGhxmzxfdWsImplPort(WebServiceFeature... features) {
        return super.getPort(GhxmzxfdWsImplPort, GhxmzxfdWs.class, features);
    }

}
