package cn.ccccltd.webservice.construction.contract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-22T14:43:14.115+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", name = "GhxmjhtWs")
@XmlSeeAlso({ObjectFactory.class})
public interface GhxmjhtWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateContractInfo", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.UpdateContractInfo")
    @WebMethod(action = "http://contract.construction.webservice.ccccltd.cn/updateContractInfo")
    @ResponseWrapper(localName = "updateContractInfoResponse", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.UpdateContractInfoResponse")
    public cn.ccccltd.webservice.construction.contract.ReturnMessage updateContractInfo(
        @WebParam(name = "contractInfo", targetNamespace = "")
        cn.ccccltd.webservice.construction.contract.GhxmjhtVO contractInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addContractInfo", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.AddContractInfo")
    @WebMethod(action = "http://contract.construction.webservice.ccccltd.cn/addContractInfo")
    @ResponseWrapper(localName = "addContractInfoResponse", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.AddContractInfoResponse")
    public cn.ccccltd.webservice.construction.contract.ReturnMessage addContractInfo(
        @WebParam(name = "contractInfo", targetNamespace = "")
        cn.ccccltd.webservice.construction.contract.GhxmjhtVO contractInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryContractInfoByContractCode", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.QueryContractInfoByContractCode")
    @WebMethod(action = "http://contract.construction.webservice.ccccltd.cn/queryContractInfoByContractCode")
    @ResponseWrapper(localName = "queryContractInfoByContractCodeResponse", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.QueryContractInfoByContractCodeResponse")
    public cn.ccccltd.webservice.construction.contract.ReturnMessage queryContractInfoByContractCode(
        @WebParam(name = "contractCode", targetNamespace = "")
        java.lang.String contractCode
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryContractInfo", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.QueryContractInfo")
    @WebMethod(action = "http://contract.construction.webservice.ccccltd.cn/queryContractInfo")
    @ResponseWrapper(localName = "queryContractInfoResponse", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.QueryContractInfoResponse")
    public cn.ccccltd.webservice.construction.contract.ReturnMessage queryContractInfo(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "zjhyfl", targetNamespace = "")
        java.lang.String zjhyfl,
        @WebParam(name = "xmszd", targetNamespace = "")
        java.lang.String xmszd,
        @WebParam(name = "xmmc", targetNamespace = "")
        java.lang.String xmmc,
        @WebParam(name = "ssqy", targetNamespace = "")
        java.lang.String ssqy,
        @WebParam(name = "htmc", targetNamespace = "")
        java.lang.String htmc,
        @WebParam(name = "htqdfs", targetNamespace = "")
        java.lang.String htqdfs
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateContractScInfo", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.UpdateContractScInfo")
    @WebMethod(action = "http://contract.construction.webservice.ccccltd.cn/updateContractScInfo")
    @ResponseWrapper(localName = "updateContractScInfoResponse", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.UpdateContractScInfoResponse")
    public cn.ccccltd.webservice.construction.contract.ReturnMessage updateContractScInfo(
        @WebParam(name = "xmid", targetNamespace = "")
        java.lang.String xmid,
        @WebParam(name = "htid", targetNamespace = "")
        java.lang.String htid,
        @WebParam(name = "scgzid", targetNamespace = "")
        java.lang.String scgzid,
        @WebParam(name = "cxmid", targetNamespace = "")
        java.lang.String cxmid,
        @WebParam(name = "chtid", targetNamespace = "")
        java.lang.String chtid,
        @WebParam(name = "cscgzid", targetNamespace = "")
        java.lang.String cscgzid
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryContractInfoById", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.QueryContractInfoById")
    @WebMethod(action = "http://contract.construction.webservice.ccccltd.cn/queryContractInfoById")
    @ResponseWrapper(localName = "queryContractInfoByIdResponse", targetNamespace = "http://contract.construction.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.construction.contract.QueryContractInfoByIdResponse")
    public cn.ccccltd.webservice.construction.contract.ReturnMessage queryContractInfoById(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "recid", targetNamespace = "")
        java.lang.String recid
    );
}
