package cn.ccccltd.webservice.dict;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-31T16:25:24.987+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://dict.webservice.ccccltd.cn/", name = "ViewDictonaryWs")
@XmlSeeAlso({ObjectFactory.class})
public interface ViewDictonaryWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDict", targetNamespace = "http://dict.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.dict.GetDict")
    @WebMethod(action = "http://dict.webservice.ccccltd.cn/getDict")
    @ResponseWrapper(localName = "getDictResponse", targetNamespace = "http://dict.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.dict.GetDictResponse")
    public cn.ccccltd.webservice.dict.ReturnMessage getDict(
        @WebParam(name = "dict_code", targetNamespace = "")
        java.lang.String dictCode,
        @WebParam(name = "dict_name", targetNamespace = "")
        java.lang.String dictName,
        @WebParam(name = "dict_type", targetNamespace = "")
        java.lang.String dictType
    );
}
