
package cn.ccccltd.webservice.design.contract;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-22T14:53:24.384+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class SjxmjhtWs_SjxmjhtWsImplPort_Server{

    protected SjxmjhtWs_SjxmjhtWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SjxmjhtWsImplPortImpl();
        String address = "http://192.168.0.161:8090/waf/ws/design_contractInfo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SjxmjhtWs_SjxmjhtWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
