
package cn.ccccltd.webservice.construction.marketinfo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-15T16:13:53.405+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class GhscxxWs_GhscxxWsImplPort_Server{

    protected GhscxxWs_GhscxxWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new GhscxxWsImplPortImpl();
        String address = "http://localhost:8060/waf/ws/invest_productMarektInfo";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new GhscxxWs_GhscxxWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
