package cn.ccccltd.webservice.other.projectbaseinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-26T13:12:45.465+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", name = "QtlxmWs")
@XmlSeeAlso({ObjectFactory.class})
public interface QtlxmWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryBaseInfo", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.QueryBaseInfo")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/queryBaseInfo")
    @ResponseWrapper(localName = "queryBaseInfoResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.QueryBaseInfoResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage queryBaseInfo(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "zjhyfl", targetNamespace = "")
        java.lang.String zjhyfl,
        @WebParam(name = "xmszd", targetNamespace = "")
        java.lang.String xmszd,
        @WebParam(name = "xmmc", targetNamespace = "")
        java.lang.String xmmc,
        @WebParam(name = "ssqy", targetNamespace = "")
        java.lang.String ssqy,
        @WebParam(name = "htmc", targetNamespace = "")
        java.lang.String htmc,
        @WebParam(name = "dwqypp", targetNamespace = "")
        java.lang.String dwqypp,
        @WebParam(name = "sftz", targetNamespace = "")
        java.lang.String sftz
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryContractInfoByContractCode", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.QueryContractInfoByContractCode")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/queryContractInfoByContractCode")
    @ResponseWrapper(localName = "queryContractInfoByContractCodeResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.QueryContractInfoByContractCodeResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage queryContractInfoByContractCode(
        @WebParam(name = "contractCode", targetNamespace = "")
        java.lang.String contractCode
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateContractScInfo", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.UpdateContractScInfo")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/updateContractScInfo")
    @ResponseWrapper(localName = "updateContractScInfoResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.UpdateContractScInfoResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage updateContractScInfo(
        @WebParam(name = "xmid", targetNamespace = "")
        java.lang.String xmid,
        @WebParam(name = "cxmid", targetNamespace = "")
        java.lang.String cxmid
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.DeleteProject")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/deleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.DeleteProjectResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage deleteProject(
        @WebParam(name = "baserecid", targetNamespace = "")
        java.lang.String baserecid
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addBaseInfo", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.AddBaseInfo")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/addBaseInfo")
    @ResponseWrapper(localName = "addBaseInfoResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.AddBaseInfoResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage addBaseInfo(
        @WebParam(name = "projectBaseInfo", targetNamespace = "")
        cn.ccccltd.webservice.other.projectbaseinfo.QtlxmVO projectBaseInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateBaseInfo", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.UpdateBaseInfo")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/updateBaseInfo")
    @ResponseWrapper(localName = "updateBaseInfoResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.UpdateBaseInfoResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage updateBaseInfo(
        @WebParam(name = "projectBaseInfo", targetNamespace = "")
        cn.ccccltd.webservice.other.projectbaseinfo.QtlxmVO projectBaseInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryBaseInfoById", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.QueryBaseInfoById")
    @WebMethod(action = "http://projectbaseinfo.other.webservice.ccccltd.cn/queryBaseInfoById")
    @ResponseWrapper(localName = "queryBaseInfoByIdResponse", targetNamespace = "http://projectbaseinfo.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.projectbaseinfo.QueryBaseInfoByIdResponse")
    public cn.ccccltd.webservice.other.projectbaseinfo.ReturnMessage queryBaseInfoById(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "recid", targetNamespace = "")
        java.lang.String recid
    );
}
