package cn.ccccltd.webservice.construction.contract;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-22T14:43:14.133+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "ghxmjhtWsImpl", 
                  wsdlLocation = "http://192.168.0.161:8090/waf/ws/invest_contractInfo?wsdl",
                  targetNamespace = "http://contract.construction.webservice.ccccltd.cn/") 
public class GhxmjhtWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://contract.construction.webservice.ccccltd.cn/", "ghxmjhtWsImpl");
    public final static QName GhxmjhtWsImplPort = new QName("http://contract.construction.webservice.ccccltd.cn/", "GhxmjhtWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.161:8090/waf/ws/invest_contractInfo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GhxmjhtWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.161:8090/waf/ws/invest_contractInfo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GhxmjhtWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GhxmjhtWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GhxmjhtWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GhxmjhtWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GhxmjhtWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GhxmjhtWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GhxmjhtWs
     */
    @WebEndpoint(name = "GhxmjhtWsImplPort")
    public GhxmjhtWs getGhxmjhtWsImplPort() {
        return super.getPort(GhxmjhtWsImplPort, GhxmjhtWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GhxmjhtWs
     */
    @WebEndpoint(name = "GhxmjhtWsImplPort")
    public GhxmjhtWs getGhxmjhtWsImplPort(WebServiceFeature... features) {
        return super.getPort(GhxmjhtWsImplPort, GhxmjhtWs.class, features);
    }

}
