
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.ccccltd.webservice.construction.contract;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-22T14:43:14.087+08:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "ghxmjhtWsImpl",
                      portName = "GhxmjhtWsImplPort",
                      targetNamespace = "http://contract.construction.webservice.ccccltd.cn/",
                      wsdlLocation = "http://192.168.0.161:8090/waf/ws/invest_contractInfo?wsdl",
                      endpointInterface = "cn.ccccltd.webservice.construction.contract.GhxmjhtWs")
                      
public class GhxmjhtWsImplPortImpl implements GhxmjhtWs {

    private static final Logger LOG = Logger.getLogger(GhxmjhtWsImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.construction.contract.GhxmjhtWs#updateContractInfo(cn.ccccltd.webservice.construction.contract.GhxmjhtVO contractInfo)*
     */
    public cn.ccccltd.webservice.construction.contract.ReturnMessage updateContractInfo(cn.ccccltd.webservice.construction.contract.GhxmjhtVO contractInfo) { 
        LOG.info("Executing operation updateContractInfo");
        System.out.println(contractInfo);
        try {
            cn.ccccltd.webservice.construction.contract.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.construction.contract.GhxmjhtWs#addContractInfo(cn.ccccltd.webservice.construction.contract.GhxmjhtVO contractInfo)*
     */
    public cn.ccccltd.webservice.construction.contract.ReturnMessage addContractInfo(cn.ccccltd.webservice.construction.contract.GhxmjhtVO contractInfo) { 
        LOG.info("Executing operation addContractInfo");
        System.out.println(contractInfo);
        try {
            cn.ccccltd.webservice.construction.contract.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.construction.contract.GhxmjhtWs#queryContractInfoByContractCode(java.lang.String contractCode)*
     */
    public cn.ccccltd.webservice.construction.contract.ReturnMessage queryContractInfoByContractCode(java.lang.String contractCode) { 
        LOG.info("Executing operation queryContractInfoByContractCode");
        System.out.println(contractCode);
        try {
            cn.ccccltd.webservice.construction.contract.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.construction.contract.GhxmjhtWs#queryContractInfo(java.lang.String zzjg, java.lang.String zjhyfl, java.lang.String xmszd, java.lang.String xmmc, java.lang.String ssqy, java.lang.String htmc, java.lang.String htqdfs)*
     */
    public cn.ccccltd.webservice.construction.contract.ReturnMessage queryContractInfo(java.lang.String zzjg, java.lang.String zjhyfl, java.lang.String xmszd, java.lang.String xmmc, java.lang.String ssqy, java.lang.String htmc, java.lang.String htqdfs) { 
        LOG.info("Executing operation queryContractInfo");
        System.out.println(zzjg);
        System.out.println(zjhyfl);
        System.out.println(xmszd);
        System.out.println(xmmc);
        System.out.println(ssqy);
        System.out.println(htmc);
        System.out.println(htqdfs);
        try {
            cn.ccccltd.webservice.construction.contract.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.construction.contract.GhxmjhtWs#updateContractScInfo(java.lang.String xmid, java.lang.String htid, java.lang.String scgzid, java.lang.String cxmid, java.lang.String chtid, java.lang.String cscgzid)*
     */
    public cn.ccccltd.webservice.construction.contract.ReturnMessage updateContractScInfo(java.lang.String xmid, java.lang.String htid, java.lang.String scgzid, java.lang.String cxmid, java.lang.String chtid, java.lang.String cscgzid) { 
        LOG.info("Executing operation updateContractScInfo");
        System.out.println(xmid);
        System.out.println(htid);
        System.out.println(scgzid);
        System.out.println(cxmid);
        System.out.println(chtid);
        System.out.println(cscgzid);
        try {
            cn.ccccltd.webservice.construction.contract.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.construction.contract.GhxmjhtWs#queryContractInfoById(java.lang.String zzjg, java.lang.String recid)*
     */
    public cn.ccccltd.webservice.construction.contract.ReturnMessage queryContractInfoById(java.lang.String zzjg, java.lang.String recid) { 
        LOG.info("Executing operation queryContractInfoById");
        System.out.println(zzjg);
        System.out.println(recid);
        try {
            cn.ccccltd.webservice.construction.contract.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
