
package cn.ccccltd.webservice.design.contractchange;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:21:50.213+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class SjbghtWs_SjbghtWsImplPort_Server{

    protected SjbghtWs_SjbghtWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SjbghtWsImplPortImpl();
        String address = "http://10.17.16.33:7070/waf/ws/design_contractChange";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SjbghtWs_SjbghtWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
