package cn.ccccltd.webservice.other.contractchange;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:52:41.785+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://contractchange.other.webservice.ccccltd.cn/", name = "QtbghtWs")
@XmlSeeAlso({ObjectFactory.class})
public interface QtbghtWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateContractChange", targetNamespace = "http://contractchange.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.contractchange.UpdateContractChange")
    @WebMethod(action = "http://contractchange.other.webservice.ccccltd.cn/updateContractChange")
    @ResponseWrapper(localName = "updateContractChangeResponse", targetNamespace = "http://contractchange.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.contractchange.UpdateContractChangeResponse")
    public cn.ccccltd.webservice.other.contractchange.ReturnMessage updateContractChange(
        @WebParam(name = "qtbghtInfo", targetNamespace = "")
        cn.ccccltd.webservice.other.contractchange.QtbghtVO qtbghtInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addContractChange", targetNamespace = "http://contractchange.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.contractchange.AddContractChange")
    @WebMethod(action = "http://contractchange.other.webservice.ccccltd.cn/addContractChange")
    @ResponseWrapper(localName = "addContractChangeResponse", targetNamespace = "http://contractchange.other.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.other.contractchange.AddContractChangeResponse")
    public cn.ccccltd.webservice.other.contractchange.ReturnMessage addContractChange(
        @WebParam(name = "qtbghtInfo", targetNamespace = "")
        cn.ccccltd.webservice.other.contractchange.QtbghtVO qtbghtInfo
    );
}
