
package cn.ccccltd.webservice.other.contractchange;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:52:41.796+08:00
 * Generated source version: 3.1.8
 * 
 */
 
public class QtbghtWs_QtbghtWsImplPort_Server{

    protected QtbghtWs_QtbghtWsImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new QtbghtWsImplPortImpl();
        String address = "http://10.17.16.33:7070/waf/ws/other_contractChange";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new QtbghtWs_QtbghtWsImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
