
package cn.ccccltd.webservice.other.contractchange;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:52:41.743+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class QtbghtWs_QtbghtWsImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://contractchange.other.webservice.ccccltd.cn/", "QtbghtWsImpl");

    private QtbghtWs_QtbghtWsImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = QtbghtWsImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        QtbghtWsImpl ss = new QtbghtWsImpl(wsdlURL, SERVICE_NAME);
        QtbghtWs port = ss.getQtbghtWsImplPort();  
        
        {
        System.out.println("Invoking updateContractChange...");
        cn.ccccltd.webservice.other.contractchange.QtbghtVO _updateContractChange_qtbghtInfo = null;
        cn.ccccltd.webservice.other.contractchange.ReturnMessage _updateContractChange__return = port.updateContractChange(_updateContractChange_qtbghtInfo);
        System.out.println("updateContractChange.result=" + _updateContractChange__return);


        }
        {
        System.out.println("Invoking addContractChange...");
        cn.ccccltd.webservice.other.contractchange.QtbghtVO _addContractChange_qtbghtInfo = null;
        cn.ccccltd.webservice.other.contractchange.ReturnMessage _addContractChange__return = port.addContractChange(_addContractChange_qtbghtInfo);
        System.out.println("addContractChange.result=" + _addContractChange__return);


        }

        System.exit(0);
    }

}
