package cn.ccccltd.webservice.construction.contractchange;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:50:21.001+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "sgbghtWsImpl", 
                  wsdlLocation = "http://10.17.16.33:7070/waf/ws/invest_contractChange?wsdl",
                  targetNamespace = "http://contractchange.construction.webservice.ccccltd.cn/") 
public class SgbghtWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://contractchange.construction.webservice.ccccltd.cn/", "sgbghtWsImpl");
    public final static QName SgbghtWsImplPort = new QName("http://contractchange.construction.webservice.ccccltd.cn/", "SgbghtWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.17.16.33:7070/waf/ws/invest_contractChange?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SgbghtWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.17.16.33:7070/waf/ws/invest_contractChange?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SgbghtWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SgbghtWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SgbghtWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SgbghtWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SgbghtWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SgbghtWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SgbghtWs
     */
    @WebEndpoint(name = "SgbghtWsImplPort")
    public SgbghtWs getSgbghtWsImplPort() {
        return super.getPort(SgbghtWsImplPort, SgbghtWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SgbghtWs
     */
    @WebEndpoint(name = "SgbghtWsImplPort")
    public SgbghtWs getSgbghtWsImplPort(WebServiceFeature... features) {
        return super.getPort(SgbghtWsImplPort, SgbghtWs.class, features);
    }

}
