
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.ccccltd.webservice.design.contractchange;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-17T17:21:50.182+08:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "sjbghtWsImpl",
                      portName = "SjbghtWsImplPort",
                      targetNamespace = "http://contractchange.design.webservice.ccccltd.cn/",
                      wsdlLocation = "http://10.17.16.33:7070/waf/ws/design_contractChange?wsdl",
                      endpointInterface = "cn.ccccltd.webservice.design.contractchange.SjbghtWs")
                      
public class SjbghtWsImplPortImpl implements SjbghtWs {

    private static final Logger LOG = Logger.getLogger(SjbghtWsImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.design.contractchange.SjbghtWs#addContractChange(cn.ccccltd.webservice.design.contractchange.SjbghtVO sjbghtInfo)*
     */
    public cn.ccccltd.webservice.design.contractchange.ReturnMessage addContractChange(cn.ccccltd.webservice.design.contractchange.SjbghtVO sjbghtInfo) { 
        LOG.info("Executing operation addContractChange");
        System.out.println(sjbghtInfo);
        try {
            cn.ccccltd.webservice.design.contractchange.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see cn.ccccltd.webservice.design.contractchange.SjbghtWs#updateContractChange(cn.ccccltd.webservice.design.contractchange.SjbghtVO sjbghtInfo)*
     */
    public cn.ccccltd.webservice.design.contractchange.ReturnMessage updateContractChange(cn.ccccltd.webservice.design.contractchange.SjbghtVO sjbghtInfo) { 
        LOG.info("Executing operation updateContractChange");
        System.out.println(sjbghtInfo);
        try {
            cn.ccccltd.webservice.design.contractchange.ReturnMessage _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
