package cn.ccccltd.webservice.construction.marketinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-15T16:13:53.482+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "ghscxxWsImpl", 
                  wsdlLocation = "http://localhost:8060/waf/ws/invest_productMarektInfo?wsdl",
                  targetNamespace = "http://marketinfo.construction.webservice.ccccltd.cn/") 
public class GhscxxWsImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://marketinfo.construction.webservice.ccccltd.cn/", "ghscxxWsImpl");
    public final static QName GhscxxWsImplPort = new QName("http://marketinfo.construction.webservice.ccccltd.cn/", "GhscxxWsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8060/waf/ws/invest_productMarektInfo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GhscxxWsImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8060/waf/ws/invest_productMarektInfo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GhscxxWsImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GhscxxWsImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GhscxxWsImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GhscxxWsImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GhscxxWsImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GhscxxWsImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GhscxxWs
     */
    @WebEndpoint(name = "GhscxxWsImplPort")
    public GhscxxWs getGhscxxWsImplPort() {
        return super.getPort(GhscxxWsImplPort, GhscxxWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GhscxxWs
     */
    @WebEndpoint(name = "GhscxxWsImplPort")
    public GhscxxWs getGhscxxWsImplPort(WebServiceFeature... features) {
        return super.getPort(GhscxxWsImplPort, GhscxxWs.class, features);
    }

}
