package cn.ccccltd.webservice.design.marketinfo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-03-14T16:55:50.913+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", name = "SjscxxWs")
@XmlSeeAlso({ObjectFactory.class})
public interface SjscxxWs {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "queryMarketInfoById", targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.design.marketinfo.QueryMarketInfoById")
    @WebMethod(action = "http://marketinfo.design.webservice.ccccltd.cn/queryMarketInfoById")
    @ResponseWrapper(localName = "queryMarketInfoByIdResponse", targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.design.marketinfo.QueryMarketInfoByIdResponse")
    public cn.ccccltd.webservice.design.marketinfo.ReturnMessage queryMarketInfoById(
        @WebParam(name = "zzjg", targetNamespace = "")
        java.lang.String zzjg,
        @WebParam(name = "recid", targetNamespace = "")
        java.lang.String recid
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addMarketInfo", targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.design.marketinfo.AddMarketInfo")
    @WebMethod(action = "http://marketinfo.design.webservice.ccccltd.cn/addMarketInfo")
    @ResponseWrapper(localName = "addMarketInfoResponse", targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.design.marketinfo.AddMarketInfoResponse")
    public cn.ccccltd.webservice.design.marketinfo.ReturnMessage addMarketInfo(
        @WebParam(name = "projectMarketInfo", targetNamespace = "")
        cn.ccccltd.webservice.design.marketinfo.SjscxxVO projectMarketInfo
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "updateMarketInfo", targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.design.marketinfo.UpdateMarketInfo")
    @WebMethod(action = "http://marketinfo.design.webservice.ccccltd.cn/updateMarketInfo")
    @ResponseWrapper(localName = "updateMarketInfoResponse", targetNamespace = "http://marketinfo.design.webservice.ccccltd.cn/", className = "cn.ccccltd.webservice.design.marketinfo.UpdateMarketInfoResponse")
    public cn.ccccltd.webservice.design.marketinfo.ReturnMessage updateMarketInfo(
        @WebParam(name = "projectMarketInfo", targetNamespace = "")
        cn.ccccltd.webservice.design.marketinfo.SjscxxVO projectMarketInfo
    );
}
